export interface ExercisePreset {
  name: string;
  machineType: 'Barbell' | 'Dumbbell' | 'Machine' | 'Cable' | 'Bodyweight';
  musclePath: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  weightStep: number;
  targetSets: number;
  targetReps: number;
  restSeconds: number;
  videoLink?: string;
}

export const EXERCISE_PRESETS: ExercisePreset[] = [
  // CHEST
  {
    name: 'Barbell Bench Press',
    machineType: 'Barbell',
    musclePath: 'Chest/Mid Chest',
    primaryMuscles: ['mid-chest'],
    secondaryMuscles: ['triceps', 'front-delts'],
    weightStep: 2.5,
    targetSets: 3,
    targetReps: 10,
    restSeconds: 120,
    videoLink: 'https://www.youtube.com/shorts/0cXAp6WhSj4',
  },
  {
    name: 'Incline Dumbbell Press',
    machineType: 'Dumbbell',
    musclePath: 'Chest/Upper Chest',
    primaryMuscles: ['upper-chest'],
    secondaryMuscles: ['triceps', 'front-delts'],
    weightStep: 2,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 90,
    videoLink: 'https://www.youtube.com/shorts/8fXfwG4ftaQ',
  },
  {
    name: 'Machine Chest Press',
    machineType: 'Machine',
    musclePath: 'Chest/Mid Chest',
    primaryMuscles: ['mid-chest'],
    secondaryMuscles: ['triceps', 'front-delts'],
    weightStep: 5,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 90,
    // videoLink: 'https://www.youtube.com/shorts/7N_p_q7z5mE', // Generic machine chest press search result from knowledge
  },
  {
    name: 'Cable Chest Fly',
    machineType: 'Cable',
    musclePath: 'Chest/Mid Chest',
    primaryMuscles: ['mid-chest'],
    secondaryMuscles: [],
    weightStep: 1,
    targetSets: 3,
    targetReps: 15,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/14VcTQz6h-8',
  },
  {
    name: 'Push-ups',
    machineType: 'Bodyweight',
    musclePath: 'Chest/Mid Chest',
    primaryMuscles: ['mid-chest'],
    secondaryMuscles: ['triceps', 'front-delts'],
    weightStep: 0,
    targetSets: 3,
    targetReps: 20,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/watch?v=AAcODQoJi2A',
  },

  // BACK
  {
    name: 'Pull-ups',
    machineType: 'Bodyweight',
    musclePath: 'Back/Lats',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper-back'],
    weightStep: 0,
    targetSets: 3,
    targetReps: 8,
    restSeconds: 120,
    videoLink: 'https://www.youtube.com/shorts/eDP_OOhMTZ4',
  },
  {
    name: 'Lat Pulldown',
    machineType: 'Machine',
    musclePath: 'Back/Lats',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper-back'],
    weightStep: 5,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 90,
    videoLink: 'https://www.youtube.com/shorts/bNmvKpJSWKM',
  },
  {
    name: 'Seated Row Machine',
    machineType: 'Machine',
    musclePath: 'Back/Upper Back',
    primaryMuscles: ['upper-back'],
    secondaryMuscles: ['lats', 'biceps'],
    weightStep: 5,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 90,
    videoLink: 'https://www.youtube.com/shorts/FTwvmczf7bE',
  },
  {
    name: 'Barbell Row',
    machineType: 'Barbell',
    musclePath: 'Back/Upper Back',
    primaryMuscles: ['upper-back'],
    secondaryMuscles: ['lats', 'biceps', 'lower-back'],
    weightStep: 2.5,
    targetSets: 3,
    targetReps: 10,
    restSeconds: 120,
    videoLink: 'https://www.youtube.com/shorts/Nqh7q3zDCoQ',
  },
  {
    name: 'Deadlift (Barbell)',
    machineType: 'Barbell',
    musclePath: 'Back/Lower Back',
    primaryMuscles: ['lower-back', 'glutes', 'hamstrings'],
    secondaryMuscles: ['upper-back', 'forearms'],
    weightStep: 5,
    targetSets: 3,
    targetReps: 5,
    restSeconds: 180,
    videoLink: 'https://www.youtube.com/shorts/xNwpvDuZJ3k',
  },

  // SHOULDERS
  {
    name: 'Overhead Press (Barbell)',
    machineType: 'Barbell',
    musclePath: 'Shoulders/Front Delts',
    primaryMuscles: ['front-delts'],
    secondaryMuscles: ['side-delts', 'triceps'],
    weightStep: 2.5,
    targetSets: 3,
    targetReps: 10,
    restSeconds: 120,
    videoLink: 'https://www.youtube.com/shorts/zoN5EH50Dro',
  },
  {
    name: 'Machine Shoulder Press',
    machineType: 'Machine',
    musclePath: 'Shoulders/Front Delts',
    primaryMuscles: ['front-delts'],
    secondaryMuscles: ['side-delts', 'triceps'],
    weightStep: 5,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 90,
    // videoLink: 'https://www.youtube.com/shorts/27_L5iY6Z9A', // Found a generic one
  },
  {
    name: 'Dumbbell Shoulder Press',
    machineType: 'Dumbbell',
    musclePath: 'Shoulders/Front Delts',
    primaryMuscles: ['front-delts'],
    secondaryMuscles: ['side-delts', 'triceps'],
    weightStep: 2,
    targetSets: 3,
    targetReps: 10,
    restSeconds: 90,
    videoLink: 'https://www.youtube.com/shorts/k6tzKisR3NY',
  },
  {
    name: 'Dumbbell Lateral Raise',
    machineType: 'Dumbbell',
    musclePath: 'Shoulders/Side Delts',
    primaryMuscles: ['side-delts'],
    secondaryMuscles: [],
    weightStep: 1,
    targetSets: 3,
    targetReps: 15,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/Kl3LEzQ5Zqs',
  },
  {
    name: 'Face Pulls (Cable)',
    machineType: 'Cable',
    musclePath: 'Shoulders/Rear Delts',
    primaryMuscles: ['rear-delts'],
    secondaryMuscles: ['upper-back'],
    weightStep: 2.5,
    targetSets: 3,
    targetReps: 15,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/qEyoBOpvqR4',
  },

  // ARMS
  {
    name: 'Cable Bicep Curl',
    machineType: 'Cable',
    musclePath: 'Arms/Biceps',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    weightStep: 2.5,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 60,
    // videoLink: 'https://www.youtube.com/shorts/Z_zI7H2p_Z4', // Generic cable curl
  },
  {
    name: 'Dumbbell Bicep Curl',
    machineType: 'Dumbbell',
    musclePath: 'Arms/Biceps',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    weightStep: 2,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/MKWBV29S6c0',
  },
  {
    name: 'Hammer Curls',
    machineType: 'Dumbbell',
    musclePath: 'Arms/Forearms',
    primaryMuscles: ['forearms', 'biceps'],
    secondaryMuscles: [],
    weightStep: 2,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/8H5oWMNWWeQ',
  },
  {
    name: 'Tricep Pushdown (Cable)',
    machineType: 'Cable',
    musclePath: 'Arms/Triceps',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    weightStep: 2.5,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/XpeCPOHJTK8',
  },
  {
    name: 'Skullcrushers (EZ Bar)',
    machineType: 'Barbell',
    musclePath: 'Arms/Triceps',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    weightStep: 2.5,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 90,
    videoLink: 'https://www.youtube.com/shorts/gTrlbuuMufQ',
  },

  // LEGS
  {
    name: 'Back Squat (Barbell)',
    machineType: 'Barbell',
    musclePath: 'Legs/Quads',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings', 'lower-back'],
    weightStep: 5,
    targetSets: 3,
    targetReps: 8,
    restSeconds: 180,
    videoLink: 'https://www.youtube.com/shorts/dW3zj79xfrc',
  },
  {
    name: 'Leg Press',
    machineType: 'Machine',
    musclePath: 'Legs/Quads',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    weightStep: 10,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 120,
    videoLink: 'https://www.youtube.com/shorts/EotSw18oR9w',
  },
  {
    name: 'Leg Extension',
    machineType: 'Machine',
    musclePath: 'Legs/Quads',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    weightStep: 5,
    targetSets: 3,
    targetReps: 15,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/iQ92TuvBqRo',
  },
  {
    name: 'Seated Leg Curl',
    machineType: 'Machine',
    musclePath: 'Legs/Hamstrings',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes'],
    weightStep: 5,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/NxPR7G_YNHI',
  },
  {
    name: 'Lying Leg Curl',
    machineType: 'Machine',
    musclePath: 'Legs/Hamstrings',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes'],
    weightStep: 5,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/watch?v=Xns7MhuvD8o',
  },
  {
    name: 'Bulgarian Split Squat',
    machineType: 'Dumbbell',
    musclePath: 'Legs/Quads',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    weightStep: 2,
    targetSets: 3,
    targetReps: 8,
    restSeconds: 90,
    videoLink: 'https://www.youtube.com/shorts/or1frhkjBDc',
  },
  {
    name: 'Romanian Deadlift (Barbell)',
    machineType: 'Barbell',
    musclePath: 'Legs/Hamstrings',
    primaryMuscles: ['hamstrings', 'glutes', 'lower-back'],
    secondaryMuscles: ['forearms'],
    weightStep: 5,
    targetSets: 3,
    targetReps: 10,
    restSeconds: 120,
    videoLink: 'https://www.youtube.com/shorts/vnEANU7BqqY',
  },
  {
    name: 'Calf Raise',
    machineType: 'Machine',
    musclePath: 'Legs/Calves',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    weightStep: 5,
    targetSets: 4,
    targetReps: 15,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/fOfPwmb5FXU',
  },

  // CORE
  {
    name: 'Crunch',
    machineType: 'Bodyweight',
    musclePath: 'Core/Abs',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    weightStep: 0,
    targetSets: 3,
    targetReps: 20,
    restSeconds: 60,
    // videoLink: 'https://www.youtube.com/shorts/XIDvN6A4_0s', // Found a crunch one
  },
  {
    name: 'Plank',
    machineType: 'Bodyweight',
    musclePath: 'Core/Abs',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    weightStep: 0,
    targetSets: 3,
    targetReps: 60,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/v25dawSzRTM',
  },
  {
    name: 'Hanging Leg Raise',
    machineType: 'Bodyweight',
    musclePath: 'Core/Abs',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    weightStep: 0,
    targetSets: 3,
    targetReps: 12,
    restSeconds: 60,
    videoLink: 'https://www.youtube.com/shorts/2n4UqRIJyk4',
  },
];
